# Generated by Django 5.2.7 on 2025-10-22 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameboardtilestate',
            name='board_tile',
            field=models.ForeignKey(blank=True, help_text='DEPRECATED: Use board_position instead', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_states', to='game.boardtile'),
        ),
        migrations.AlterField(
            model_name='tile',
            name='tile_type',
            field=models.CharField(choices=[('UTILITY', 'Utility'), ('CHANCE', 'Chance'), ('TREASURE', 'Treasure'), ('TAX', 'Tax'), ('START', 'Start'), ('JAIL', 'Jail'), ('GO_TO_JAIL', 'GoToJail'), ('FREE_PARKING', 'FreeParking'), ('VACATION', 'Vacation'), ('CUSTOM', 'Custom')], default='CUSTOM', max_length=20),
        ),
        migrations.CreateModel(
            name='BoardPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(help_text='Position index on the board. Must be in range [0, board.size*board.size - 1].')),
                ('override_action', models.JSONField(blank=True, default=dict)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='game.board')),
                ('city', models.ForeignKey(blank=True, help_text='Reference to a property/city tile', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='board_positions', to='game.city')),
                ('tile', models.ForeignKey(blank=True, help_text='Reference to a non-property tile (START, JAIL, CHANCE, etc.)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='board_positions', to='game.tile')),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('board', 'position')},
            },
        ),
        migrations.AddField(
            model_name='gameboardtilestate',
            name='board_position',
            field=models.ForeignKey(blank=True, help_text='Reference to BoardPosition (new schema)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_states', to='game.boardposition'),
        ),
    ]
