# Generated by Django 5.2.7 on 2025-10-21 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('ended', 'Ended'), ('cancelled', 'Cancelled')], default='active', max_length=10, verbose_name='Status')),
                ('starting_price', models.PositiveIntegerField(default=0, verbose_name='Starting Price')),
                ('current_price', models.PositiveIntegerField(default=0, verbose_name='Current Price')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Started At')),
                ('ends_at', models.DateTimeField(blank=True, null=True, verbose_name='Ends At')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auctions', to='game.game', verbose_name='Game')),
                ('highest_bidder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_auctions', to='game.player', verbose_name='Highest Bidder')),
                ('started_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='started_auctions', to='game.player', verbose_name='Started By')),
                ('tile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auctions', to='game.tile', verbose_name='Tile')),
            ],
            options={
                'verbose_name': 'Auction',
                'verbose_name_plural': 'Auctions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='Amount')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='game.auction', verbose_name='Auction')),
                ('bidder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='game.player', verbose_name='Bidder')),
            ],
            options={
                'verbose_name': 'Bid',
                'verbose_name_plural': 'Bids',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deck', models.CharField(choices=[('chance', 'Chance'), ('community', 'Community Chest')], max_length=20, verbose_name='Deck')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('effect', models.JSONField(blank=True, default=dict, verbose_name='Effect')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Card',
                'verbose_name_plural': 'Cards',
                'ordering': ['deck', 'order', 'id'],
                'indexes': [models.Index(fields=['deck', 'is_active', 'order'], name='game_card_deck_7c6fef_idx')],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('player', 'Player'), ('system', 'System'), ('game', 'Game')], default='player', max_length=10, verbose_name='Message Type')),
                ('content', models.TextField(verbose_name='Content')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='game.game', verbose_name='Game')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_messages', to='game.player', verbose_name='Player')),
            ],
            options={
                'verbose_name': 'Chat Message',
                'verbose_name_plural': 'Chat Messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Minigame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minigame_type', models.CharField(choices=[('target_click', 'Target Click'), ('memory_match', 'Memory Match'), ('quick_math', 'Quick Math')], max_length=20, verbose_name='Minigame Type')),
                ('score', models.IntegerField(default=0, verbose_name='Score')),
                ('reward', models.IntegerField(default=0, verbose_name='Reward')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Is Completed')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Started At')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='minigames', to='game.game', verbose_name='Game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='minigames', to='game.player', verbose_name='Player')),
            ],
            options={
                'verbose_name': 'Minigame',
                'verbose_name_plural': 'Minigames',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('money', 'Money'), ('resource', 'Resource')], default='money', max_length=10, verbose_name='Kind')),
                ('amount', models.IntegerField(default=0, verbose_name='Amount')),
                ('resource_type', models.CharField(blank=True, max_length=20, verbose_name='Resource Type')),
                ('reason', models.CharField(blank=True, max_length=100, verbose_name='Reason')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('from_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outgoing_transactions', to='game.player', verbose_name='From')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='game.game', verbose_name='Game')),
                ('related_action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='game.action', verbose_name='Related Action')),
                ('to_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_transactions', to='game.player', verbose_name='To')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='auction',
            index=models.Index(fields=['game', 'status'], name='game_auctio_game_id_3c7077_idx'),
        ),
        migrations.AddIndex(
            model_name='auction',
            index=models.Index(fields=['tile'], name='game_auctio_tile_id_077ad7_idx'),
        ),
        migrations.AddIndex(
            model_name='auction',
            index=models.Index(fields=['-started_at'], name='game_auctio_started_ba42eb_idx'),
        ),
        migrations.AddIndex(
            model_name='bid',
            index=models.Index(fields=['auction', '-created_at'], name='game_bid_auction_6e30ee_idx'),
        ),
        migrations.AddIndex(
            model_name='bid',
            index=models.Index(fields=['bidder'], name='game_bid_bidder__a2a226_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['game', '-created_at'], name='game_chatme_game_id_6a9f14_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['player', '-created_at'], name='game_chatme_player__10942a_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['message_type'], name='game_chatme_message_1b3c93_idx'),
        ),
        migrations.AddIndex(
            model_name='minigame',
            index=models.Index(fields=['game', 'minigame_type'], name='game_miniga_game_id_d581cc_idx'),
        ),
        migrations.AddIndex(
            model_name='minigame',
            index=models.Index(fields=['player', '-started_at'], name='game_miniga_player__137b96_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['game', '-created_at'], name='game_transa_game_id_1ca5e4_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['from_player'], name='game_transa_from_pl_181fb5_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['to_player'], name='game_transa_to_play_19c8d5_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['kind'], name='game_transa_kind_c035bd_idx'),
        ),
    ]
