# Generated by Django 5.2.7 on 2025-10-21 17:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auction_bid_card_chatmessage_minigame_transaction_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='User who created this game and can start it', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_games', to=settings.AUTH_USER_MODEL, verbose_name='Game Owner'),
        ),
        migrations.AddField(
            model_name='game',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique identifier for this game session', verbose_name='Game UUID'),
        ),
        migrations.AddField(
            model_name='player',
            name='is_ready',
            field=models.BooleanField(default=False, help_text='Whether the player is ready to start the game', verbose_name='Is Ready'),
        ),
    ]
