# Generated by Django 5.2.7 on 2025-10-23 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_add_board_position_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='mode',
            field=models.CharField(choices=[('SOLO', 'Solo'), ('FRIENDS', 'Friends'), ('ONLINE', 'Online')], default='ONLINE', max_length=20),
        ),
    ]
