# Generated by Django 5.2.7 on 2025-10-21 17:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_game_owner_game_uuid_player_is_ready'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique identifier for this game session', unique=True, verbose_name='Game UUID'),
        ),
    ]
